version: '3.8'

services:
  nginx-ssl-setup:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - ENV=prod
    restart: "no"
    ports:
      - "80:80"
    networks:
      - mindful_network
    volumes:
      - nginx_logs:/var/log/nginx
      - certbot_data:/var/www/certbot
    environment:
      - DOMAIN=autonomiapro.com.br

volumes:
  nginx_logs:
    driver: local
  certbot_data:
    driver: local

networks:
  mindful_network:
    driver: bridge